# Notes: this receipt is based on torchvision-feedstock:
# https://github.com/conda-forge/torchvision-feedstock/blob/master/recipe/meta.yaml

{% set version = "2.2.1" %}
{% set torchani_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: torchani
  version: {{ version }}

source:
  url: https://github.com/aiqm/torchani/archive/refs/tags/{{ version }}.tar.gz
  sha256: c4f299a586518c57b17332309f803e6ae34c1b7a4b48d542bd6c46e9c4f8d146

build:
  number: 1
  skip: true  # [win]
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ torchani_proc_type }}                                                  # [cuda_compiler_version == "None"]
  string: py{{ CONDA_PY }}cuda{{ cuda_compiler_version|replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ torchani_proc_type }}  # [cuda_compiler_version != "None"]
  script_env:
  - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - "{{ PYTHON }} -m pip install . --global-option='--cuaev-all-sms' -vvv --no-deps"  # [cuda_compiler_version != "None"]
    - "{{ PYTHON }} -m pip install . -vvv --no-deps"                                    # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}              # [cuda_compiler_version != "None"]
    - sysroot_linux-64 ==2.17             # [linux64]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]

  host:
    - python
    - numpy
    - pip
    - setuptools ==59.5.0
    - setuptools_scm ==6.3.2
    - importlib_metadata
    - pytorch
    - pytorch-gpu {{ pytorch_version }}  # [cuda_compiler_version != "None"]
    - pytorch-cpu {{ pytorch_version }}  # [cuda_compiler_version == "None"]
    # cuda 10.2 does not have cub, which need to be manually downloaded in setup.py
    - wget                               # [cuda_compiler_version == "10.2"]
    - unzip                              # [cuda_compiler_version == "10.2"]

  run:
    - python
    - pip
    - setuptools ==59.5.0
    - setuptools_scm ==6.3.2
    - importlib_metadata
    - lark-parser
    - requests
    - h5py
    - numpy
    - pytorch
    - {{ pin_compatible('pytorch-gpu', max_pin='x.x.x') }}  # [cuda_compiler_version != "None"]
    - {{ pin_compatible('pytorch-cpu', max_pin='x.x.x') }}  # [cuda_compiler_version == "None"]

test:
  imports:
    - torchani
    - torchani.cuaev                     # [cuda_compiler_version != "None"]
  source_files:
    - torchani/resources/*
    - tests/*
    - tools/*
    - download.sh
    - dataset/*
    - test_requirements.txt
  requires:
    - wget
    - unzip
    - tensorboard
    - tqdm
    - ase
    - h5py
    - pillow
    - pyyaml
    - pytest
    - expecttest
    - pkbar
  commands:
    # download testing datasets
    - ./download.sh                                                           # [linux64]
    # broken symlink that got ignored when copying
    - ln -s ../download/dataset/ani-1x/ dataset/ani-1x                        # [linux64]
    - ln -s ../download/dataset/ani1-up_to_gdb4/ dataset/ani1-up_to_gdb4      # [linux64]
    # test
    - cd tests; python -m pytest -v -s *.py                                   # [linux64]

about:
  home: https://github.com/aiqm/torchani
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Accurate Neural Network Potential on PyTorch'

extra:
  recipe-maintainers:
    - hadim
    - yueyericardo
