{% set name = "torchani" %}
{% set version = "2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: c086fe6cabe49a0408d1f1b12aaf14e33b9e6ef0ffb15f3020792934e7c9fbbe

  git_url: https://github.com/hadim/torchani.git
  git_rev: cuda

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - pip
    - setuptools_scm
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - cub  # [cuda_compiler_version != "None"]
    - pytorch  # [cuda_compiler_version != "None"]
    - ninja  # [cuda_compiler_version != "None"]
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - setuptools
    - pytorch
    - lark-parser
    - requests
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ pin_compatible('cudatoolkit') }}  # [cuda_compiler_version != "None"]
    - nvcc_linux-64  # [cuda_compiler_version != "None"]

test:
  imports:
    - torchani

about:
  home: https://github.com/aiqm/torchani
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Accurate Neural Network Potential on PyTorch'

extra:
  recipe-maintainers:
    - hadim
