{% set name = "torchani" %}
{% set version = "2.2" %}

# Set CUDA related variables
{% if cuda_compiler_version != "None" %}
{% set cuda_build_prefix = "cuda" + cuda_compiler_version|string %}
{% else %}
{% set cuda_build_prefix = "" %}
{% endif %}

{% set build_number = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: c086fe6cabe49a0408d1f1b12aaf14e33b9e6ef0ffb15f3020792934e7c9fbbe

  git_url: https://github.com/hadim/torchani.git
  git_rev: cuda

build:
  number: {{ build_number }}
  string: {{ cuda_build_prefix }}py{{ py }}h{{ PKG_HASH }}_{{ build_number }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - pip
    - setuptools_scm
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - cub  # [cuda_compiler_version != "None"]
    - {{ pin_compatible('pytorch') }}  # [cuda_compiler_version != "None"]
    - ninja  # [cuda_compiler_version != "None"]
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - setuptools
    - pytorch
    - lark-parser
    - requests

test:
  imports:
    - torchani
    - cuaev  # [cuda_compiler_version != "None"]

about:
  home: https://github.com/aiqm/torchani
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Accurate Neural Network Potential on PyTorch'

extra:
  recipe-maintainers:
    - hadim
