{% set name = "torchani" %}
{% set version = "2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: c086fe6cabe49a0408d1f1b12aaf14e33b9e6ef0ffb15f3020792934e7c9fbbe

  git_url: https://github.com/akkamesh/torchani.git
  git_rev: enh-ext-aev
  
build:
  skip: True  # [win]
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
    - cub
    - pytorch
  host:
    - python
    - pip
  run:
    - python
    - setuptools  # required for pkg_resources
    - pytorch
    - lark-parser
    - requests
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ pin_compatible('cudatoolkit-dev') }}
    - nvcc_linux-64

test:
  imports:
    - torchani

about:
  home: https://github.com/aiqm/torchani
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Accurate Neural Network Potential on PyTorch'

extra:
  recipe-maintainers:
    - hadim
